### ISSUE TITLE
No module named cv2

### ISSUE THREAD

**Issue by yuchuangu85** [amarlearning/opencv#3]
ImportError: No module named cv2,where can find the cv2? Thank you!

**Comment by amarlearning** [comment]
Hi @yuchuangu85, you can refer to this documentation on how to [download cv2](https://docs.opencv.org/3.4.1/d2/de6/tutorial_py_setup_in_ubuntu.html)

Use this command ```sudo apt-get install python-opencv``` to install cv2 in ubuntu.

**Comment by yuchuangu85** [comment]
@amarlearning Thank you!

**Comment by amarlearning** [comment]
I am closing this, feel free to reopen in case of any other queries. :smile:
